// Mapea el codename interno de cada Pal (el que aparece en nombres de clase
// como BP_PinkCat_C) a su nombre real en el juego. 316 especies, incluye
// variantes elementales, jefes de raid/mundo y contenido especial. Fuente:
// https://github.com/tseven17/Palworld-IDs (extraido de
// Pal/Content/Pal/DataTable/Character/DT_PalMonsterParameter.uasset, la
// data table real del juego).
const PAL_SPECIES_NAMES = {
  "Alpaca": "Melpaca",
  "AmaterasuWolf": "Kitsun",
  "AmaterasuWolf_Dark": "Kitsun Noct",
  "Anubis": "Anubis",
  "BadCatgirl": "Nyafia",
  "Baphomet": "Incineram",
  "Baphomet_Dark": "Incineram Noct",
  "Bastet": "Mau",
  "Bastet_Ice": "Mau Cryst",
  "BerryGoat": "Caprity",
  "BerryGoat_Dark": "Caprity Noct",
  "BirdDragon": "Vanwyrm",
  "BirdDragon_Ice": "Vanwyrm Cryst",
  "BlackCentaur": "Necromus",
  "BlackFurDragon": "Dragostrophe",
  "BlackGriffon": "Shadowbeak",
  "BlackMetalDragon": "Astegon",
  "BlackPuppy": "Smokie",
  "BlackPuppy_Ice": "Smokie Cryst",
  "BlueberryFairy": "Prunelia",
  "BlueDragon": "Azurobe",
  "BlueDragon_Ice": "Azurobe Cryst",
  "BluePlatypus": "Fuack",
  "BluePlatypus_Fire": "Fuack Ignis",
  "BlueSkyDragon": "Shaolong",
  "BlueThunderHorse": "Azurmane",
  "Boar": "Rushoar",
  "BrownRabbit": "Lapiron",
  "CactusDoll": "Needoll",
  "CactusDoll_Dark": "Needoll Noct",
  "CandleGhost": "Sootseer",
  "CandleWitch": "Unidentified Pal",
  "CaptainPenguin": "Penking",
  "CaptainPenguin_Black": "Penking Lux",
  "Carbunclo": "Lifmunk",
  "CatBat": "Tombat",
  "CatMage": "Katress",
  "CatMage_Fire": "Katress Ignis",
  "CatVampire": "Felbat",
  "ChickenPal": "Chikipi",
  "ClioneTwins": "Amione",
  "CloverFairy": "Clovee",
  "ClownRabbit": "Dupin",
  "ColorfulBird": "Tocotoco",
  "CowPal": "Mozzarina",
  "CubeTurtle": "Tetroise",
  "CubeTurtle_Neutral": "Tetroise Primo",
  "CuteButterfly": "Cinnamoth",
  "CuteFox": "Vixy",
  "CuteMole": "Fuddler",
  "DandelionGirl": "Souffline",
  "DarkAlien": "Xenovader",
  "DarkCrow": "Cawgnito",
  "DarkFlameFox": "Majex",
  "DarkMechaDragon": "Xenolord",
  "DarkScorpion": "Menasting",
  "DarkScorpion_Ground": "Menasting Terra",
  "Deer": "Eikthyrdeer",
  "Deer_Ground": "Eikthyrdeer Terra",
  "DessertBoss": "Marcus & Faleris",
  "DomeArmorDragon": "Aegidron",
  "DreamDemon": "Daedream",
  "DrillGame": "Digtoise",
  "Eagle": "Galeclaw",
  "ElecCat": "Sparkit",
  "ElecLion": "Boltmane",
  "ElecLizard": "Slowatt",
  "ElecPanda": "Grizzbolt",
  "ElecPomeranian": "Puffolt",
  "ElecSnail": "Snock",
  "ElecSnail_Ground": "Snock Lux",
  "FairyDragon": "Elphidran",
  "FairyDragon_Water": "Elphidran Aqua",
  "FeatherOstrich": "Dazemu",
  "FengyunDeeper": "Fenglope",
  "FengyunDeeper_Electric": "Fenglope Lux",
  "FireKirin": "Pyrin",
  "FireKirin_Dark": "Pyrin Noct",
  "FlameBambi": "Rooby",
  "FlameBuffalo": "Arsox",
  "FlowerDinosaur": "Dinossom",
  "FlowerDinosaur_Electric": "Dinossom Lux",
  "FlowerDoll": "Petallia",
  "FlowerDoll_Fire": "Petallia Ignis",
  "FlowerPrince": "Dandilord",
  "FlowerRabbit": "Flopie",
  "FluffyBird": "Muffly",
  "FlyingManta": "Celaray",
  "FlyingManta_Thunder": "Celaray Lux",
  "ForestBoss": "Lily & Lyleen",
  "FoxExorcist": "Flaracle",
  "FoxMage": "Wixen",
  "FoxMage_Dark": "Wixen Noct",
  "Ganesha": "Teafant",
  "Garm": "Direhowl",
  "GhostAnglerfish": "Ghangler",
  "GhostAnglerfish_Fire": "Ghangler Ignis",
  "GhostBeast": "Maraith",
  "GhostBlackCat": "Wispaw",
  "GhostDragon": "Eidrolon",
  "GhostDragon_Fire": "Eidrolon Ignis",
  "GhostRabbit": "Nitemary",
  "GhostRabbit_Grass": "Nitemary Botan",
  "GoldenHorse": "Gildane",
  "Gorilla": "Gorirat",
  "Gorilla_Ground": "Gorirat Terra",
  "GrassBoss": "Zoe & Grizzbolt",
  "GrassGolem": "Dualith",
  "GrassGolem_Dark": "Dualith Noct",
  "GrassMammoth": "Mammorest",
  "GrassMammoth_Ice": "Mammorest Cryst",
  "GrassMinotaur": "Elgrove",
  "GrassMinotaur_Ice": "Elgrove Cryst",
  "GrassPanda": "Mossanda",
  "GrassPanda_Electric": "Mossanda Lux",
  "GrassRabbitMan": "Verdash",
  "GrimGirl": "Splatterina",
  "GuardianDog": "Yakumo",
  "HadesBird": "Helzephyr",
  "HadesBird_Electric": "Helzephyr Lux",
  "HawkBird": "Nitewing",
  "Hedgehog": "Jolthog",
  "Hedgehog_Ice": "Jolthog Cryst",
  "HerculesBeetle": "Warsect",
  "HerculesBeetle_Ground": "Warsect Terra",
  "HoodGhost": "Hoodle",
  "Horus": "Faleris",
  "Horus_Water": "Faleris Aqua",
  "IceCrocodile": "Munchill",
  "IceDeer": "Reindrix",
  "IceFox": "Foxcicle",
  "IceHorse": "Frostallion",
  "IceHorse_Dark": "Frostallion Noct",
  "IceNarwhal": "Whalaska",
  "IceNarwhal_Fire": "Whalaska Ignis",
  "IceSeal": "Polapup",
  "IceSeal_Ground": "Polapup Terra",
  "IceWitch": "Icelyn",
  "JellyfishFairy": "Jelliette",
  "JellyfishGhost": "Jellroy",
  "JetDragon": "Jetragon",
  "KabukiMan": "Renjishi",
  "Kelpie": "Kelpsea",
  "Kelpie_Fire": "Kelpsea Ignis",
  "KendoFrog": "Croajiro",
  "KendoFrog_Dark": "Croajiro Noct",
  "KingAlpaca": "Kingpaca",
  "KingAlpaca_Ice": "Kingpaca Cryst",
  "KingBahamut": "Blazamut",
  "KingBahamut_Dragon": "Blazamut Ryu",
  "KingSunfish": "Solmora",
  "KingSunfish_Thunder": "Solmora Lux",
  "KingWhale": "Panthalus",
  "Kirin": "Univolt",
  "Kirin_Ice": "Univolt Cryst",
  "Kitsunebi": "Foxparks",
  "Kitsunebi_Ice": "Foxparks Cryst",
  "LanternButler": "Loomen",
  "LastBoss": "Zenara & Astralym",
  "LavaGirl": "Flambelle",
  "LazyCatfish": "Dumud",
  "LazyCatfish_Gold": "Dumud Gild",
  "LazyDragon": "Relaxaurus",
  "LazyDragon_Electric": "Relaxaurus Lux",
  "LeafMomonga": "Herbil",
  "LeafPrincess": "Lullu",
  "LegendDeer": "Hartalis",
  "LilyQueen": "Lyleen",
  "LilyQueen_Dark": "Lyleen Noct",
  "LittleBriarRose": "Bristla",
  "LizardMan": "Leezpunk",
  "LizardMan_Fire": "Leezpunk Ignis",
  "LongCat": "Valentail",
  "LotusDragon": "Ophydia",
  "Manticore": "Blazehowl",
  "Manticore_Dark": "Blazehowl Noct",
  "MimicDog": "Mimog",
  "Monkey": "Tanzee",
  "Monkey_Fire": "Tanzee Ignis",
  "MonochromeQueen": "Solenne",
  "MoonChild": "Wistella",
  "MoonQueen": "Selyne",
  "MopBaby": "Swee",
  "MopKing": "Sweepa",
  "Mothman": "Silvance",
  "MummyPal": "Gildra",
  "MushroomDragon": "Shroomer",
  "MushroomDragon_Dark": "Shroomer Noct",
  "MushroomLady": "Mycora",
  "Mutant": "Lunaris",
  "MysteryMask": "Omascul",
  "NaughtyCat": "Grintale",
  "NegativeKoala": "Depresso",
  "NegativeOctopus": "Killamari",
  "NegativeOctopus_Neutral": "Killamari Primo",
  "NightBlueHorse": "Starryon",
  "NightBlueHorse_Neutral": "Starryon Primo",
  "NightFox": "Nox",
  "NightLady": "Bellanoir",
  "NightLady_Dark": "Bellanoir Libero",
  "OctopusGirl": "Gloopie",
  "OctopusGirl_Neutral": "Gloopie Primo",
  "OniGhostGirl": "Bakemi",
  "PandaGirl": "Leafan",
  "Penguin": "Pengullet",
  "Penguin_Electric": "Pengullet Lux",
  "PinkCat": "Cattiva",
  "PinkLizard": "Lovander",
  "PinkRabbit": "Ribbuny",
  "PinkRabbit_Grass": "Ribbuny Botan",
  "PlantSlime": "Gumoss",
  "Plesiosaur": "Braloha",
  "POLICE_PalRide": "PIDF Rider",
  "PoseidonOrca": "Neptilius",
  "PurpleSpider": "Tarantriss",
  "QueenBee": "Elizabee",
  "RAID_YakushimaBoss001_Green": "True Eye of Cthulhu",
  "RAID_YakushimaBoss002": "Moon Lord",
  "RaijinDaughter": "Dazzi",
  "RaijinDaughter_Water": "Dazzi Noct",
  "RedArmorBird": "Ragnahawk",
  "RedFlowerBird": "Tropicaw",
  "RobinHood": "Robinquill",
  "RobinHood_Ground": "Robinquill Terra",
  "RockBeast": "Pierdon",
  "RockBeast_Ice": "Pierdon Cryst",
  "Ronin": "Bushi",
  "Ronin_Dark": "Bushi Noct",
  "SaintCentaur": "Paladius",
  "SakurajimaBoss": "Saya & Selyne",
  "SakuraSaurus": "Broncherry",
  "SakuraSaurus_Water": "Broncherry Aqua",
  "SamuraiDog": "Pupperai",
  "ScorpionMan": "Prixter",
  "ScorpionMan_Electric": "Prixter Lux",
  "Sekhmet": "Sekhmet",
  "Serpent": "Surfent",
  "Serpent_Ground": "Surfent Terra",
  "SharkKid": "Gobfin",
  "SharkKid_Fire": "Gobfin Ignis",
  "SheepBall": "Lamball",
  "SifuDog": "Dogen",
  "SkyDragon": "Quivern",
  "SkyDragon_Grass": "Quivern Botan",
  "SleeveRabbit": "Lapure",
  "SmallArmadillo": "Kikit",
  "SmallYeti": "Snugloo",
  "SnakeGirl": "Venusa",
  "SnowBoss": "Victor & Shadowbeak",
  "SnowPeafowl": "Frostplume",
  "SnowTigerBeastman": "Bastigor",
  "SoldierBee": "Beegarde",
  "SorajimaBoss": "Auri & Shaolong",
  "StrawHatCat": "Unidentified Pal",
  "StuffedShark": "Finsider",
  "StuffedShark_Fire": "Finsider Ignis",
  "SumoDog": "Bulldosu",
  "Suzaku": "Suzaku",
  "Suzaku_Water": "Suzaku Aqua",
  "SweetsSheep": "Woolipop",
  "SweetsSheep_Ground": "Woolipop Terra",
  "SwordCutlassfish": "Skutlass",
  "SwordCutlassfish_Fire": "Skutlass Ignis",
  "TentacleTurtle": "Turtacle",
  "TentacleTurtle_Ground": "Turtacle Terra",
  "ThiefBird": "Roujay",
  "ThunderBird": "Beakon",
  "ThunderBird_Ice": "Beakon Cryst",
  "ThunderDog": "Rayhound",
  "ThunderDog_Ice": "Rayhound Cryst",
  "ThunderDragonMan": "Orserk",
  "ThunderFluffyBird": "Dynamoff",
  "TropicalOstrich": "Palumba",
  "Umihebi": "Jormuntide",
  "Umihebi_Fire": "Jormuntide Ignis",
  "VenusFlytrap": "Carnibora",
  "VikingBoss": "Bjorn & Bastigor",
  "VioletFairy": "Vaelet",
  "VolcanicMonster": "Reptyro",
  "VolcanicMonster_Ice": "Reptyro Cryst",
  "VolcanicTurtle": "Unidentified Pal",
  "VolcanoBoss": "Axel & Orserk",
  "VolcanoDragon": "Moldron",
  "VolcanoDragon_Ice": "Moldron Cryst",
  "WeaselDragon": "Chillet",
  "WeaselDragon_Fire": "Chillet Ignis",
  "Werewolf": "Loupmoon",
  "Werewolf_Ice": "Loupmoon Cryst",
  "WhiteAlienDragon": "Xenogard",
  "WhiteDeer": "Celesdir",
  "WhiteDeer_Dark": "Celesdir Noct",
  "WhiteMoth": "Sibelyx",
  "WhiteMoth_Neutral": "Sibelyx Primo",
  "WhiteShieldDragon": "Silvegis",
  "WhiteTiger": "Cryolinx",
  "WhiteTiger_Ground": "Cryolinx Terra",
  "WindChimes": "Hangyu",
  "WindChimes_Ice": "Hangyu Cryst",
  "WingGolem": "Knocklem",
  "WingGolem_Fire": "Knocklem Ignis",
  "WizardOwl": "Hoocrates",
  "WoolFox": "Cremis",
  "WorldTreeDragon": "Astralym",
  "YakushimaBoss001": "Eye of Cthulhu",
  "YakushimaBoss001_Small": "Demon Eye",
  "YakushimaMonster001": "Green Slime",
  "YakushimaMonster001_Blue": "Blue Slime",
  "YakushimaMonster001_Pink": "Illuminant Slime",
  "YakushimaMonster001_Purple": "Purple Slime",
  "YakushimaMonster001_Rainbow": "Rainbow Slime",
  "YakushimaMonster001_Red": "Red Slime",
  "YakushimaMonster002": "Enchanted Sword",
  "YakushimaMonster003": "Cave Bat",
  "YakushimaMonster003_Purple": "Illuminant Bat",
  "Yeti": "Wumpo",
  "Yeti_Grass": "Wumpo Botan",
};

// Variantes grandes/jefe (ej. "MopKing_BOSS") no siempre tienen entrada ni
// icono propio en la tabla/CDN; se resuelven con los del Pal base.
const VARIANT_SUFFIXES = ['_BOSS', '_Alpha'];

function resolveBaseCodename(codename) {
  if (PAL_SPECIES_NAMES[codename]) return codename;
  for (const suffix of VARIANT_SUFFIXES) {
    if (codename.endsWith(suffix)) {
      const base = codename.slice(0, -suffix.length);
      if (PAL_SPECIES_NAMES[base]) return base;
    }
  }
  return null;
}

/** Convierte un codename interno (ej. "PinkCat", tomado de BP_PinkCat_C) a su nombre real. */
function palDisplayName(codename) {
  const base = resolveBaseCodename(codename);
  return base ? PAL_SPECIES_NAMES[base] : codename;
}

/** URL del icono del Pal (CDN publico de paldb.cc). Null si no se pudo resolver un codename conocido. */
function palIconUrl(codename) {
  const base = resolveBaseCodename(codename);
  if (!base) return null;
  return `https://cdn.paldb.cc/image/Pal/Texture/PalIcon/Normal/T_${base}_icon_normal.webp`;
}

module.exports = { PAL_SPECIES_NAMES, palDisplayName, palIconUrl };
