// Mapea el codename interno de cada Pal (el que aparece en nombres de clase
// como BP_PinkCat_C) a su nombre real en el juego. Fuente:
// https://palworld.wiki.gg/wiki/Pals_/_Internal_names
const PAL_SPECIES_NAMES = {
  Alpaca: 'Melpaca',
  AmaterasuWolf: 'Kitsun',
  Anubis: 'Anubis',
  BadCatgirl: 'Nyafia',
  Baphomet: 'Incineram',
  Baphomet_Dark: 'Incineram Noct',
  Bastet: 'Mau',
  Bastet_Ice: 'Mau Cryst',
  BerryGoat: 'Caprity',
  BirdDragon: 'Vanwyrm',
  BirdDragon_Ice: 'Vanwyrm Cryst',
  BlackCentaur: 'Necromus',
  BlackFurDragon: 'Dragostrophe',
  BlackGriffon: 'Shadowbeak',
  BlackMetalDragon: 'Astegon',
  BlueberryFairy: 'Prunelia',
  BlueDragon: 'Azurobe',
  BluePlatypus: 'Fuack',
  Boar: 'Rushoar',
  CandleGhost: 'Sootseer',
  CaptainPenguin: 'Penking',
  Carbunclo: 'Lifmunk',
  CatBat: 'Tombat',
  CatMage: 'Katress',
  CatMage_Fire: 'Katress Ignis',
  CatVampire: 'Felbat',
  ChickenPal: 'Chikipi',
  ColorfulBird: 'Tocotoco',
  CowPal: 'Mozzarina',
  CuteButterfly: 'Cinnamoth',
  CuteFox: 'Vixy',
  CuteMole: 'Fuddler',
  DarkAlien: 'Xenovader',
  DarkCrow: 'Cawgnito',
  DarkMutant: 'Dark Mutant',
  DarkScorpion: 'Menasting',
  DarkScorpion_Ground: 'Menasting Terra',
  Deer: 'Eikthyrdeer',
  Deer_Ground: 'Eikthyrdeer Terra',
  DreamDemon: 'Daedream',
  DrillGame: 'Digtoise',
  Eagle: 'Galeclaw',
  ElecCat: 'Sparkit',
  ElecLion: 'Boltmane',
  ElecPanda: 'Grizzbolt',
  FairyDragon: 'Elphidran',
  FairyDragon_Water: 'Elphidran Aqua',
  FeatherOstrich: 'Dazemu',
  FengyunDeeper: 'Fenglope',
  FireKirin: 'Pyrin',
  FireKirin_Dark: 'Pyrin Noct',
  FlameBambi: 'Rooby',
  FlameBuffalo: 'Arsox',
  FlowerDinosaur: 'Dinossom',
  FlowerDinosaur_Electric: 'Dinossom Lux',
  FlowerDoll: 'Petallia',
  FlowerRabbit: 'Flopie',
  FlyingManta: 'Celaray',
  FoxMage: 'Wixen',
  FoxMage_Dark: 'Wixen Noct',
  Ganesha: 'Teafant',
  Garm: 'Direhowl',
  GhostBeast: 'Maraith',
  Gorilla: 'Gorirat',
  Gorilla_Ground: 'Gorirat Terra',
  GrassMammoth: 'Mammorest',
  GrassMammoth_Ice: 'Mammorest Cryst',
  GrassPanda: 'Mossanda',
  GrassPanda_Electric: 'Mossanda Lux',
  GrassRabbitMan: 'Verdash',
  GuardianDog: 'Yakumo',
  HadesBird: 'Helzephyr',
  HadesBird_Electric: 'Helzephyr Lux',
  HawkBird: 'Nitewing',
  Hedgehog: 'Jolthog',
  Hedgehog_Ice: 'Jolthog Cryst',
  HerculesBeetle: 'Warsect',
  HerculesBeetle_Ground: 'Warsect Terra',
  Horus: 'Faleris',
  IceDeer: 'Reindrix',
  IceFox: 'Foxcicle',
  IceHorse: 'Frostallion',
  IceHorse_Dark: 'Frostallion Noct',
  JetDragon: 'Jetragon',
  Kelpie: 'Kelpsea',
  Kelpie_Fire: 'Kelpsea Ignis',
  KendoFrog: 'Croajiro',
  KingAlpaca: 'Kingpaca',
  KingAlpaca_Ice: 'Kingpaca Cryst',
  KingBahamut: 'Blazamut',
  KingBahamut_Dragon: 'Blazamut Ryu',
  Kirin: 'Univolt',
  Kitsunebi: 'Foxparks',
  LavaGirl: 'Flambelle',
  LazyCatfish: 'Dumud',
  LazyDragon: 'Relaxaurus',
  LazyDragon_Electric: 'Relaxaurus Lux',
  LeafPrincess: 'Lullu',
  LilyQueen: 'Lyleen',
  LilyQueen_Dark: 'Lyleen Noct',
  LittleBriarRose: 'Bristla',
  LizardMan: 'Leezpunk',
  LizardMan_Fire: 'Leezpunk Ignis',
  Manticore: 'Blazehowl',
  Manticore_Dark: 'Blazehowl Noct',
  MimicDog: 'Mimog',
  Monkey: 'Tanzee',
  MoonQueen: 'Selyne',
  MopBaby: 'Swee',
  MopKing: 'Sweepa',
  MushroomDragon: 'Shroomer',
  MushroomDragon_Dark: 'Shroomer Noct',
  Mutant: 'Lunaris',
  NaughtyCat: 'Grintale',
  NegativeKoala: 'Depresso',
  NegativeOctopus: 'Killamari',
  NightBlueHorse: 'Starryon',
  NightFox: 'Nox',
  NightLady: 'Bellanoir',
  NightLady_Dark: 'Bellanoir Libero',
  Penguin: 'Pengullet',
  PinkCat: 'Cattiva',
  PinkLizard: 'Lovander',
  PinkRabbit: 'Ribbuny',
  PlantSlime: 'Gumoss',
  PlantSlime_Flower: 'Gumoss (Special)',
  QueenBee: 'Elizabee',
  RaijinDaughter: 'Dazzi',
  RedArmorBird: 'Ragnahawk',
  RobinHood: 'Robinquill',
  RobinHood_Ground: 'Robinquill Terra',
  Ronin: 'Bushi',
  Ronin_Dark: 'Bushi Noct',
  SaintCentaur: 'Paladius',
  SakuraSaurus: 'Broncherry',
  SakuraSaurus_Water: 'Broncherry Aqua',
  ScorpionMan: 'Prixter',
  Serpent: 'Surfent',
  Serpent_Ground: 'Surfent Terra',
  SharkKid: 'Gobfin',
  SharkKid_Fire: 'Gobfin Ignis',
  SheepBall: 'Lamball',
  SifuDog: 'Dogen',
  SkyDragon: 'Quivern',
  SkyDragon_Grass: 'Quivern Botan',
  SmallArmadillo: 'Kikit',
  SoldierBee: 'Beegarde',
  Suzaku: 'Suzaku',
  Suzaku_Water: 'Suzaku Aqua',
  SweetsSheep: 'Woolipop',
  ThunderBird: 'Beakon',
  ThunderDog: 'Rayhound',
  ThunderDragonMan: 'Orserk',
  Umihebi: 'Jormuntide',
  Umihebi_Fire: 'Jormuntide Ignis',
  VioletFairy: 'Vaelet',
  VolcanicMonster: 'Reptyro',
  VolcanicMonster_Ice: 'Reptyro Cryst',
  WeaselDragon: 'Chillet',
  WeaselDragon_Fire: 'Chillet Ignis',
  Werewolf: 'Loupmoon',
  WhiteAlienDragon: 'Xenogard',
  WhiteDeer: 'Celesdir',
  WhiteMoth: 'Sibelyx',
  WhiteShieldDragon: 'Silvegis',
  WhiteTiger: 'Cryolinx',
  WindChimes: 'Hangyu',
  WindChimes_Ice: 'Hangyu Cryst',
  WingGolem: 'Knocklem',
  WizardOwl: 'Hoocrates',
  WoolFox: 'Cremis',
  Yeti: 'Wumpo',
  Yeti_Grass: 'Wumpo Botan',
};

/** Convierte un codename interno (ej. "PinkCat", tomado de BP_PinkCat_C) a su nombre real. */
function palDisplayName(codename) {
  return PAL_SPECIES_NAMES[codename] || codename;
}

module.exports = { PAL_SPECIES_NAMES, palDisplayName };
